# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1541df2f1bc450dbb1b7075012e53dee5536a6e7cd1b8d8d1fb5e6be4240b50fb9a1b9228eaa65998af879e7bf3f98d71a123d96ed96783dc995a1f31659e06

test:
  secret_key_base: 3e8b79c12447d4f850f13e78cdff61239d8d4d6d8ca8fea9189dddb4c4a36f547632502a53be0bcf8c1cc0459234c29975fd409cadcd878878ab426763ef8830

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
